insert into ville(nom_ville)
values('Pittsburg'),
('Normal'),
('Hattiesburg'),
('Laredo'),
('Kannapolis'),
('Omaha'),
('Compton'),
('Beaumont'),
('Orland Park'),
('Bell Gardens'),
('Fort Wayne'),
('Fishers'),
('Newport News'),
('Clifton'),
('Jersey City'),
('Macon-Bibb County'),
('Davie'),
('Bartlett'),
('Bellevue'),
('Waltham'),
('Port Orange'),
('Warren'),
('Novi'),
('Boca Raton'),
('North Richland Hills'),
('Mesa');